/*
 *Generated by hal-cmake
 */
#ifndef HAL_CMAKE_TEMPLATES_EVENTCUTTEMPLATE_H_
#define HAL_CMAKE_TEMPLATES_EVENTCUTTEMPLATE_H_

#include <Hal/EventCut.h>

namespace MyHal {
  class Hal::Package;
  class EventCutTemplate : public Hal::EventCut {
  public:
    EventCutTemplate();
    Int_t Init(Int_t taskID);
    Bool_t Pass(Hal::Event* pair);
    Hal::Package* Report() const;
    virtual ~EventCutTemplate();
    ClassDef(EventCutTemplate, 1)
  };

}  // namespace MyHal

#endif /* HAL_CMAKE_TEMPLATES_EVENTCUTTEMPLATE_H_*/
