/*
 *Generated by hal-cmake
 */
#include "TrackTemplate.h"

namespace Hal {

  TrackTemplate::TrackTemplate() {
    // TODO Auto-generated constructor stub
  }

  TrackTemplate::~TrackTemplate() {
    // TODO Auto-generated destructor stub
  }

} /* namespace Hal */
