/*
 *Generated by hal-cmake
 */
#ifndef HAL_CMAKE_TEMPLATES_TRACKTEMPLATE_H_
#define HAL_CMAKE_TEMPLATES_TRACKTEMPLATE_H_

#include <Hal/Track.h>
namespace MyHal {

  class TrackTemplate : public Hal::Track {
    /**
     * add your fields, your getters, and setters
     */
  public:
    TrackTemplate();
    Int_t Init(Int_t taskID);
    Bool_t Pass(Hal::Track* pair);
    Hal::Package* Report() const;
    virtual ~TrackTemplate();
    ClassDef(TrackTemplate, 1)
  };

}  // namespace MyHal

#endif /* HAL_CMAKE_TEMPLATES_TRACKTEMPLATE_H_ */
