/*
 *Generated by hal-cmake
 */
#ifndef HAL_CMAKE_TEMPLATES_TWOTRACKCUTTEMPLATE_H_
#define HAL_CMAKE_TEMPLATES_TWOTRACKCUTTEMPLATE_H_

#include <Hal/TwoTrackCut.h>

namespace MyHal {
  class Hal::Package;
  class TwoTrackCutTemplate : public Hal::TwoTrackCut {
  public:
    TwoTrackCutTemplate();
    Int_t Init(Int_t taskID);
    Bool_t Pass(Hal::TwoTrack* pair);
    Hal::Package* Report() const;
    virtual ~TwoTrackCutTemplate() {};
    ClassDef(TwoTrackCutTemplate, 1)
  };

}  // namespace MyHal

#endif /* HAL_TEMPLATES_TWOTRACKCUTTEMPLATE_H_ */
