CMAKE_MINIMUM_REQUIRED(VERSION 3.11.0 FATAL_ERROR)


#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -g -Wshadow")

set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake/modules"  ${CMAKE_MODULE_PATH})
set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake/fair"  ${CMAKE_MODULE_PATH})
include(HalMacros)
SET(FAIRROOT_LIBRARY_PROPERTIES ${FAIRROOT_LIBRARY_PROPERTIES}
  VERSION "${HAL_VERSION}"
  SOVERSION "${HAL_MAJOR_VERSION}"
)

#set(CXX11_COMPILER_FLAGS "-std=c++11")

include(CheckCXXCompilerFlag)

include(FairMacros)
include(Hal)
include(CheckCompiler)
include(WriteConfig)


PathInfo()
   
Set(LIBRARY_OUTPUT_PATH "${CMAKE_BINARY_DIR}/lib")
Set(EXECUTABLE_OUTPUT_PATH "${CMAKE_BINARY_DIR}/bin")
Set(INCLUDE_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}/include")
Set(STANDALONE TRUE)


find_package(ROOT 6.00.00 REQUIRED)
if("${ROOT_VERSION_MAJOR}.${ROOT_VERSION_MINOR}" VERSION_GREATER 6.16)
  Execute_Process(COMMAND ${ROOT_CONFIG_EXECUTABLE} --has-vmc OUTPUT_VARIABLE ROOT_vmc_FOUND)
  String(STRIP ${ROOT_vmc_FOUND} ROOT_vmc_FOUND)
#If(NOT ROOT_vmc_FOUND) we don't need VMC in stand-alone installation
#  set(CMAKE_PREFIX_PATH $ENV{SIMPATH} ${CMAKE_PREFIX_PATH})
 # find_package2(PUBLIC VMC REQUIRED)
 # set(VMCLIB VMCLibrary)
#  endif()
endif()


Message("-- Looking for GSL ...")
find_package(GSL)
if(NOT GSL_FOUND)
  if(APPLE)
   set(GSL_DIR /usr/local)
  else()
    #unset(GSL_DIR)
    execute_process(COMMAND gsl-config --prefix OUTPUT_VARIABLE GSL_DIR OUTPUT_STRIP_TRAILING_WHITESPACE)
  endif()
  
  find_package(GSL REQUIRED)
endif()

  Set(SYSTEM_INCLUDE_DIRECTORIES
    ${ROOT_INCLUDE_DIR}
 #   ${Boost_INCLUDE_DIRS}
  )
  Set(ROOT_INCLUDE_PATH
        ${BASE_INCLUDE_DIRECTORIES}
  )

Set(BASE_INCLUDE_DIRECTORIES ${BASE_INCLUDE_DIRECTORIES} ${VMC_INCLUDE_DIRS} ${SYSTEM_INCLUDE_DIRECTORIES} )
SET(HALLIBDIR ${CMAKE_BINARY_DIR}/lib)  
SET(LD_LIBRARY_PATH  ${HALLIBDIR} ${GSL_LIBRARY_DIR} ${LD_LIBRARY_PATH})

Check_Compiler()

